### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jaanos** [jernejbanevec/Upravljanje-maloprodajnega-prostora#2]
Vidim, da imata na repozitoriju celotno navidezno okolje (mapa `venv`). Ker je vsebina te mape odvisna od sistema, kjer se poganja program, ne sodi na repozitorij. Prav tako na repozitorij ne sodi mapa `.idea` z nastavitvami urejevalnika.

Zato svetujem, da mapi odstranita (lahko seveda na repozitorij dasta skripto ali navodila za vzpostavitev navideznega okolja) ter dodasta datoteko `.gitignore` - lahko uporabita kar predlogo za [Python](https://github.com/github/gitignore/blob/master/Python.gitignore), ki že vsebuje `venv`, ter dodasta še vrstico `.idea`, da tudi ta mapa ne bo šla na repozitorij.

**Comment by jernejbanevec** [comment]
Mapi sta odstranjeni ter datoteka '.gitignore' je dodana, tako da issue zapiram. Lepo pozdravljeni in hvala za opozorilo.
